# This file was generated by pkgs.mastodon.updateScript.
{
  fetchFromGitHub,
  applyPatches,
  patches ? [ ],
}:
let
  version = "4.4.0-rc.1";
in
applyPatches {
  src = fetchFromGitHub {
    owner = "mastodon";
    repo = "mastodon";
    rev = "v${version}";
    hash = "sha256-XYynIVFR/4FFj1S260vHF7qBZIgq3/C0N3+2+hbzPtw=";
    passthru = {
      inherit version;
      yarnHash = "sha256-Qh2jli99rxrT10KVGKnePxP6RXYIjtehDCJB5PfOngM=";
      yarnMissingHashes = ./missing-hashes.json;
    };
  };
  patches = patches ++ [ ];
}
